server:
  port: 8077

dubbo:
  application:
    name: demo-application
    qos-enable: false
    register-mode: interface
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848?namespace=public&register-consumer-url=true